# copyright: 2024 EUMETSAT
# license: LICENSE.txt
name: cmts_learn_osi_saf_sst
channels:
  - conda-forge
  - cmts
  - eumetsat
dependencies:
  - conda-forge::python
  - conda-forge::jupyterlab
  - conda-forge::netcdf4
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::ipywidgets
  - conda-forge::jupyter_nbextensions_configurator
  - conda-forge::ipykernel
  - conda-forge::cmocean
  - conda-forge::cmcrameri
  - conda-forge::requests
  - conda-forge::xarray
  - conda-forge::pydap
  - eumetsat::eumdac
